[package]
name = "Flipper"
version = "0.1.0"
edition = "2021"



[workspace]
members =[
    "flipper_core",
    "flipper_server",
    "flipper_client"
]

[[bin]]
name = "flipper_server"
path = "flipper_server/src/main.rs"

[[bin]]
name = "flipper_client_bin"
path = "flipper_client/src/main.rs"