[package]
name = "flipper_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flipper_core = {path="../flipper_core"}
anyhow = "1.0.65"
clap = "3.2.22"
tokio = {version = "1.21.1"}